[project]
name = "nexus-rpc"
version = "0.1.0"
description = "Nexus Python SDK"
readme = "README.md"
authors = [
    { name = "Dan Davison", email = "dandavison7@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "typing-extensions>=4.12.2",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pyright>=1.1.400",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.11.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nexusrpc"]

[tool.pyright]
include = ["src", "tests"]

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
extend-ignore = ["E741"]  # Allow single-letter variable names like I, O

