name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-test-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9', '3.13', '3.14']
        os: [ubuntu-latest, ubuntu-arm, macos-intel, macos-arm, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Lint and type check
        run: uv run poe lint

      - name: Run tests
        run: |
          uv run pytest --cov=src --cov-report=html:coverage_html_report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report-${{ matrix.os }}-${{ matrix.python-version }}
          path: coverage_html_report/

      - name: Build API docs
        run: uv run poe docs

      - name: Deploy prod API docs
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel deploy build/apidocs -t ${{ secrets.VERCEL_TOKEN }} --prod --yes
