name: CI

on:
  push:
    branches: [ main, v0 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # TODO(preview): other platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.13', '3.14']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Lint
        run: |
          uv run ruff format --check
          uv run ruff check

      - name: Type check
        # TODO(preview): Get both passing
        run: |
          uv run pyright .
          uv run mypy --check-untyped-defs . || true

      - name: Run tests
        run: |
          uv run pytest --cov=src --cov-report=html:coverage_html_report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report-${{ matrix.python-version }}
          path: coverage_html_report/

      - name: Build API docs
        run: uv run pydoctor src/nexusrpc

      - name: Deploy prod API docs
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel deploy build/apidocs -t ${{ secrets.VERCEL_TOKEN }} --prod --yes
